2014-08-26 05:07:33,170 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:07:33,186 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:08:15,727 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:08:15,727 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:09:43,324 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:09:43,325 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:10:09,418 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:10:09,419 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:14:56,132 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:14:56,132 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:16:06,395 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:16:06,396 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:17]
2014-08-26 05:16:06,396 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:16:44,274 INFO: NOW LOADED [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-26 05:16:44,276 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:16:44,276 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:17]
2014-08-26 05:16:44,277 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:16:48,321 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:16]
2014-08-26 05:16:48,322 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:17]
2014-08-26 05:16:48,322 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:18]
2014-08-26 05:27:33,205 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 05:28:16,350 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 05:28:16,351 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:28:16,352 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:28:16,352 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:28:20,828 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:28:20,829 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:28:20,829 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:28:34,208 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 05:28:34,209 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:28:34,209 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:28:34,210 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:37:23,223 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 05:37:23,224 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:37:23,225 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:37:23,225 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:37:28,038 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:37:28,038 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:37:28,039 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:37:32,394 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:37:32,395 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:37:32,395 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:37:49,841 ERROR: err [in /opt/Excerpts/excerpts/__init__.py:9]
2014-08-26 05:37:49,841 WARNING: warn [in /opt/Excerpts/excerpts/__init__.py:10]
2014-08-26 05:37:49,842 INFO: IN HERE INFO [in /opt/Excerpts/excerpts/__init__.py:11]
2014-08-26 05:44:00,641 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 05:45:58,589 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 05:50:35,808 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:27:59,452 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:31:24,798 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:31:24,810 INFO: teardown [in /opt/Excerpts/excerpts/__init__.py:20]
2014-08-26 06:31:30,697 INFO: teardown [in /opt/Excerpts/excerpts/__init__.py:20]
2014-08-26 06:33:56,034 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:41:55,067 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:44:35,656 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:49:37,810 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:56:46,695 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 06:56:46,697 ERROR: Exception on / [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 11, in hello
    p = Pages(contents="HI THIS IS COOL, and a test.")
TypeError: 'module' object is not callable
2014-08-26 06:56:46,698 ERROR: 'module' object is not callable [in /opt/Excerpts/excerpts/__init__.py:16]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 11, in hello
    p = Pages(contents="HI THIS IS COOL, and a test.")
TypeError: 'module' object is not callable
2014-08-26 07:00:03,916 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-26 07:04:58,065 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 04:21:13,774 ERROR: Exception on / [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 13, in hello
    db_session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (OperationalError) (2006, 'MySQL server has gone away') 'INSERT INTO pages (contents) VALUES (%s)' ('It worked!',)
2014-08-27 04:21:13,796 ERROR: (OperationalError) (2006, 'MySQL server has gone away') 'INSERT INTO pages (contents) VALUES (%s)' ('It worked!',) [in /opt/Excerpts/excerpts/__init__.py:18]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 13, in hello
    db_session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (OperationalError) (2006, 'MySQL server has gone away') 'INSERT INTO pages (contents) VALUES (%s)' ('It worked!',)
2014-08-27 04:52:08,843 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 04:53:07,959 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 04:58:19,496 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 04:58:58,389 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:00:35,613 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:01:23,165 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:01:52,880 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:04:27,331 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:10:33,967 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:11:08,220 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:14:45,603 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:15:29,453 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:17:13,353 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:17:42,241 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:18:45,343 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:18:59,397 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:20:38,227 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:24:17,434 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:26:09,006 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:27:58,240 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:28:33,782 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:30:32,187 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:31:37,991 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:32:29,565 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:34:39,915 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:35:02,290 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:35:13,376 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:35:48,405 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:35:58,851 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:36:13,631 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:38:22,692 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:38:36,639 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:39:29,233 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:45:45,939 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:45:59,091 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:46:14,758 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:49:09,147 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:49:13,235 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:53:02,905 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 05:57:49,374 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 06:41:39,198 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:14:36,518 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:14:36,521 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:15:30,663 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:15:30,698 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:16:39,101 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:16:39,105 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:16:39,105 INFO: False [in /opt/Excerpts/excerpts/__init__.py:14]
2014-08-27 07:17:22,805 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:17:22,805 INFO: False [in /opt/Excerpts/excerpts/__init__.py:14]
2014-08-27 07:17:31,939 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:17:31,943 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:17:31,943 INFO: hi [in /opt/Excerpts/excerpts/__init__.py:14]
2014-08-27 07:17:31,944 INFO: False [in /opt/Excerpts/excerpts/__init__.py:15]
2014-08-27 07:19:32,057 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:19:32,060 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:19:32,061 INFO: hi [in /opt/Excerpts/excerpts/__init__.py:14]
2014-08-27 07:19:32,061 INFO: False [in /opt/Excerpts/excerpts/__init__.py:15]
2014-08-27 07:20:33,933 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:20:33,937 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:20:33,937 INFO: hi [in /opt/Excerpts/excerpts/__init__.py:14]
2014-08-27 07:20:33,937 INFO: True [in /opt/Excerpts/excerpts/__init__.py:15]
2014-08-27 07:44:08,467 INFO: (u'$t1nkyS0ck$',) [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:44:08,468 INFO: hi [in /opt/Excerpts/excerpts/__init__.py:14]
2014-08-27 07:44:08,468 INFO: True [in /opt/Excerpts/excerpts/__init__.py:15]
2014-08-27 07:50:56,609 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:50:56,612 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:51:33,633 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:51:41,199 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:51:41,202 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:52:04,609 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:52:05,036 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:52:10,655 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:52:14,399 INFO: True [in /opt/Excerpts/excerpts/__init__.py:13]
2014-08-27 07:54:03,040 INFO: {u'test': 1, u'alex': u'ressler'} [in /opt/Excerpts/excerpts/__init__.py:19]
2014-08-27 07:54:03,043 INFO: True [in /opt/Excerpts/excerpts/__init__.py:21]
2014-08-27 07:57:46,576 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:57:46,577 INFO: {u'password': u'$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:19]
2014-08-27 07:57:46,580 ERROR: Exception on /verify [POST] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 21, in verify
    app.logger.info(password.password == _json.password)
AttributeError: 'dict' object has no attribute 'password'
2014-08-27 07:57:46,582 ERROR: 'dict' object has no attribute 'password' [in /opt/Excerpts/excerpts/__init__.py:45]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 21, in verify
    app.logger.info(password.password == _json.password)
AttributeError: 'dict' object has no attribute 'password'
2014-08-27 07:58:28,896 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-27 07:58:28,898 INFO: {u'password': u'$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:19]
2014-08-27 07:58:28,900 INFO: True [in /opt/Excerpts/excerpts/__init__.py:21]
2014-08-27 07:58:34,008 INFO: {u'password': u'$t1nk2yS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:19]
2014-08-27 07:58:34,015 INFO: False [in /opt/Excerpts/excerpts/__init__.py:21]
2014-08-27 07:58:38,764 INFO: {u'password': u'$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:19]
2014-08-27 07:58:38,767 INFO: True [in /opt/Excerpts/excerpts/__init__.py:21]
2014-08-28 03:14:26,754 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:19:06,628 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:19:06,630 INFO: None [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:19:36,327 INFO: {'username': 'admin', 'password': '$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:21:20,737 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:21:20,738 INFO: None [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:21:39,977 INFO: {'username': 'admin', 'password': '$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:22:03,990 INFO: {'username': 'admin', 'password': '$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:22:05,888 INFO: {'username': 'admin', 'password': '$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:23:01,825 INFO: None [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:23:11,628 INFO: {'username': 'admin', 'password': '$t1nkyS0ck$'} [in /opt/Excerpts/excerpts/__init__.py:36]
2014-08-28 03:26:07,766 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:26:07,767 ERROR: Exception on / [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 37, in decorated
    app.logger.critical("Failed auth attempt for: %s, %s" % (auth.username, auth.password))
AttributeError: 'NoneType' object has no attribute 'username'
2014-08-28 03:26:07,769 ERROR: 'NoneType' object has no attribute 'username' [in /opt/Excerpts/excerpts/__init__.py:72]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 37, in decorated
    app.logger.critical("Failed auth attempt for: %s, %s" % (auth.username, auth.password))
AttributeError: 'NoneType' object has no attribute 'username'
2014-08-28 03:26:49,902 ERROR: Exception on / [GET] [in /usr/local/lib/python2.7/dist-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 37, in decorated
    app.logger.critical("Failed auth attempt for: %s, %s" % (auth.username, auth.password))
AttributeError: 'NoneType' object has no attribute 'username'
2014-08-28 03:26:49,903 ERROR: 'NoneType' object has no attribute 'username' [in /opt/Excerpts/excerpts/__init__.py:72]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Excerpts/excerpts/__init__.py", line 37, in decorated
    app.logger.critical("Failed auth attempt for: %s, %s" % (auth.username, auth.password))
AttributeError: 'NoneType' object has no attribute 'username'
2014-08-28 03:27:24,613 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:30:00,118 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:30:51,328 CRITICAL: Failed auth attempt for: af, dfsdfs [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:30:57,674 CRITICAL: Failed auth attempt for: afafaf, fadsfdsfsdf [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:03,533 CRITICAL: Failed auth attempt for: afafadfd, sdfdsfsdf [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:06,834 CRITICAL: Failed auth attempt for: afaf, affd [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:10,170 CRITICAL: Failed auth attempt for: sdf, d [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:13,535 CRITICAL: Failed auth attempt for: fdd,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:14,452 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:15,000 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:15,653 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:16,087 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:16,334 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:16,708 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:16,889 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:17,086 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:17,303 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:17,509 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:17,719 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:17,912 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:31:18,125 CRITICAL: Failed auth attempt for: ,  [in /opt/Excerpts/excerpts/__init__.py:38]
2014-08-28 03:32:08,977 INFO: NOW LOADED [in /opt/Excerpts/apache/excerpts.wsgi:14]
2014-08-28 03:43:53,989 CRITICAL: Failed auth attempt for: admin, $t1nky$0ck$ [in /opt/Excerpts/excerpts/__init__.py:39]
